Repository Selleo/DevPath, pull requests merged in 2020-04, with the labels that each got.

#11 extract GIT part from junior 1
  README.md
  common/git.md
  frontend_developer/01_junior_I.md
Labels: enhancement

#12 Javascript prerequisites
  README.md
Labels: apply feedback, enhancement

#13 Backend Junior 1
  README.md
  backend_developer/01_junior_I.md
Labels: enhancement, ready to merge

#14 Backend Junior 2
  README.md
  backend_developer/02_junior_II.md
Labels: enhancement

#15 Added Linux path with merged MacOS path
  common/git.md
  common/linux.md
  common/macos.md
  frontend_developer/01_junior_I.md
Labels: enhancement

#7 Update gatsby requirements in React lvl 3
  frontend_developer/react/03_level_3.md
Labels: Ready for Review

#19 Update README with Systems links
  README.md
Labels: Ready for Review, enhancement
