Repository Selleo/DevPath, pull requests merged in 2020-05, with the labels that each got.

#17 Urls checker
  .github/workflows/main.yml
  frontend_developer/01_junior_I.md
  frontend_developer/react/03_level_3.md
Labels: ready to merge

#20 Css and html
  README.md
  frontend_developer/CSS & HTML/01_junior_I.md
  frontend_developer/CSS & HTML/02_junior_II.md
  frontend_developer/CSS & HTML/03_independent_I.md
  frontend_developer/CSS & HTML/04_independent_II.md
  frontend_developer/CSS & HTML/05_independent_III.md
Labels: Ready for Review

#21 Designer path
  README.md
  designer/01_junior_I.md
  designer/02_junior_II.md
  designer/03_independent_I.md
  designer/04_independent_II.md
  designer/05_independent_III.md
  designer/06_middle_I.md
  designer/07_middle_II.md
Labels: Ready for Review

#22 Update framework comparison
  frontend_developer/react/03_level_3.md
Labels: enhancement
