Repository Selleo/DevPath, pull requests merged in 2021-03, with the labels that each got.

#85 Add Data Extraction bubble
  content/web_development/skills/data_extraction.md
Labels: apply feedback

#83 Feat: Performance and Monitoring bubble
  content/web_development/skills/performance_and_monitoring.md
Labels: apply feedback

#93 QA middle - add published article about improving process
  content/qa/middle.md
Labels: Ready for Review

#97 chore #82: add compliance-bubble v1
  content/web_development/skills/compliance.md
Labels: work in progress

#96 Wireframing and prototyping bubble
  content/web_development/skills/wireframing_and_prototyping.md
Labels: Ready for Review
